### ISSUE TITLE
Undefined function or variable 'fastmarchmex'.

### ISSUE THREAD

**Issue by Myzhencai** [llorz/SGA18_orientation_BCICP_code#1]
hi. thanks for sharing this awesome woke . I get a issue as the title , I am not familiar with the code could you please help me out . :- ) thanks .Have a nice day. @llorz 
![screenshot from 2019-01-27 16-06-15](https://user-images.githubusercontent.com/21084423/51798470-c71e7900-224d-11e9-854b-50b482af34d6.png)

**Comment by llorz** [comment]
Hi @Myzhencai,

Sorry for the late reply!

So here, the code is trying to compute the **pairwise geodesic distance** of all vertices of a shape S, and save the distance matrix to S.Gamma, where S.Gamma( i , j ) gives the geodesic distance between the i-th vertex and the j-th vertex.

I only have the mex file for the fast-marching algorithm in windows, that's why it does not work for your linux. Here are some possible solutions:

1. ~try windows~
2. You can use some **approximate distance matrix** to get the code work first. For example, you can save the pairwise Euclidean distance (use MATLAB pdist) to S.Gamma, in this case, the code should work, but the quality can be worse I assume.
3. In the directory: "/utils/external/geodesics_matlab/" there are mex file to compute geodesic distances that works for linux and can be used to compute S.Gamma. 

Hope this helps! Please let me know there is anything unclear :D have a nice day :)

**Comment by Myzhencai** [comment]
@llorz  ：-），thanks for help . I have made it in windows.Best wish from China .

**Comment by rFalque** [comment]
The linux version of the fastmarchmex can be found there:
[https://github.com/abbasloo/dnnAuto/blob/master/preprocessing/isc/fastmarchmex.mexa64](https://github.com/abbasloo/dnnAuto/blob/master/preprocessing/isc/fastmarchmex.mexa64)

It is substantially faster than the geodesic computation from /utils/external/geodesics_matlab/ (from 40 minutes-ish to few minutes).

Thanks for sharing your code :)

**Comment by llorz** [comment]
Thank you so much for sharing this! @rFalque Raphael Falque
